/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project;

import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author march
 */
public class Main extends javax.swing.JFrame {
     String pricest[] = {"239", "279", "329", "259", "189", "229", "189", "159", "119", "139", "159", "299",
         "39", "49", "39", "49", "39", "39", "39", "49", "49", "59", "39", "20",
        "59", "89", "29", "19", "79", "49", "79", "129", "109", "39"};
    DecimalFormat df = new DecimalFormat("#,###.00"); //สร้างค่า Colum
    DefaultTableModel model;  //สร้างโมเดลตาราง สร้างเพื่อควบคุม การเพิ่ม การลบ ในตาราง
    double total = 0; //ราคารวมทั้งหมด
    int selected; //เก็บแถวที่ผู้ใช้เลือก
    int n;  //เก็บตำแหน่งซ้ำ
    
    double money;   //เก็บราคารวม
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
         txtPriceSt.setText(pricest[0]); //เซตราคาอาหารเริ่มต้นตัวแรก
         TxtQuanity.requestFocus(); //คอเซอร์ไปอยู่ที่ จำนวนราคาตั้งแต่เริ่มรัน
        model = (DefaultTableModel) TbPayment.getModel(); //อ้างอิงจากตาราง ทั้งจำนวนคอลัม จำนวนแถว
        TbPayment.getColumnModel().getColumn(0).setPreferredWidth(1);
        TbPayment.getColumnModel().getColumn(1).setPreferredWidth(200);
        TbPayment.getColumnModel().getColumn(2).setPreferredWidth(1);
        TbPayment.getColumnModel().getColumn(3).setPreferredWidth(1);
        TbPayment.getColumnModel().getColumn(4).setPreferredWidth(1);
        TbPayment.getColumnModel().getColumn(5).setPreferredWidth(150);
    }
    public boolean check() { //เช็คข้อมุลที่ซ้ำ ระหว่างข้อมูลใน Combo box และ ใน ช้อมูลรายการอาหารในตาราง ถ้าชื่อที่จะเพิ่มซ้ำกันก็ให้นำจำนวนนั้นใาบวกเพิ่ม
        for (int i = 0; i < TbPayment.getRowCount(); i++) { //RowCount เช็คทุกแถว
            n = i;
            if ((cbbMenu.getSelectedItem().toString().equals(TbPayment.getValueAt(i, 1))) && (cbbTable.getSelectedItem().toString().equals(TbPayment.getValueAt(i, 0)))) {
                System.out.println("รายการอาหารซ่ำ ที่แถว" + n);

                return true;
            }
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFrameLeft = new javax.swing.JPanel();
        jPanelQUEUE = new javax.swing.JPanel();
        TxtQUEUE = new javax.swing.JLabel();
        jPanelInvoid = new javax.swing.JPanel();
        TxtInvoid = new javax.swing.JLabel();
        jPanelMenu = new javax.swing.JPanel();
        TxtMenu = new javax.swing.JLabel();
        jPanelPayment = new javax.swing.JPanel();
        TxtPayment = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelLogout = new javax.swing.JPanel();
        jLabelLogout = new javax.swing.JLabel();
        jPanelFrameTop = new javax.swing.JPanel();
        jTabbedPaneMainApp = new javax.swing.JTabbedPane();
        jPanelMainQueue = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanelMainMenu = new javax.swing.JPanel();
        jPanelTxtMainMenu = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        TxtMenuSelect = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        TxtMenuEditSelect = new javax.swing.JLabel();
        jTabbedPaneMainMenu = new javax.swing.JTabbedPane();
        jPanelMenuSelect = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TxtStock = new javax.swing.JTextField();
        ccbCategory = new javax.swing.JComboBox<>();
        cbbMenu = new javax.swing.JComboBox<>();
        ButtonAddProduct = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbPayment = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAreaDetail = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ButtonEditProduct = new javax.swing.JButton();
        ButtonDeleteProduct = new javax.swing.JButton();
        TxtQuanity = new javax.swing.JTextField();
        ButtonConfirm1 = new javax.swing.JButton();
        txtPriceSt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cbbTable = new javax.swing.JComboBox<>();
        jPanelMENUEDIT = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanelMainInvoice = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanelMainPayment = new javax.swing.JPanel();
        jPanelTxtMainPayment = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        TxtPaymentSelect = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        TxtAuditSelect = new javax.swing.JLabel();
        jTabbedPaneMainPayment = new javax.swing.JTabbedPane();
        jPanelPaymentSelect = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TbPaymentFramePayment = new javax.swing.JTable();
        TxtST = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        TxtChange = new javax.swing.JTextField();
        TxtCash = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ButtonConfirm2 = new javax.swing.JButton();
        ButtonConfirm = new javax.swing.JButton();
        jPanelAudit = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lertros");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFrameLeft.setBackground(new java.awt.Color(204, 204, 204));

        TxtQUEUE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtQUEUE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtQUEUE.setText("QUEUE");
        TxtQUEUE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtQUEUEMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelQUEUELayout = new javax.swing.GroupLayout(jPanelQUEUE);
        jPanelQUEUE.setLayout(jPanelQUEUELayout);
        jPanelQUEUELayout.setHorizontalGroup(
            jPanelQUEUELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtQUEUE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelQUEUELayout.setVerticalGroup(
            jPanelQUEUELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelQUEUELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtQUEUE, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        TxtInvoid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtInvoid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtInvoid.setText("INVOICE");
        TxtInvoid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtInvoidMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelInvoidLayout = new javax.swing.GroupLayout(jPanelInvoid);
        jPanelInvoid.setLayout(jPanelInvoidLayout);
        jPanelInvoidLayout.setHorizontalGroup(
            jPanelInvoidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtInvoid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelInvoidLayout.setVerticalGroup(
            jPanelInvoidLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInvoidLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtInvoid, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        TxtMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtMenu.setText("MENU");
        TxtMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtMenuMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        TxtPayment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtPayment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtPayment.setText("PAYMENT");
        TxtPayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtPaymentMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelPaymentLayout = new javax.swing.GroupLayout(jPanelPayment);
        jPanelPayment.setLayout(jPanelPaymentLayout);
        jPanelPaymentLayout.setHorizontalGroup(
            jPanelPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelPaymentLayout.setVerticalGroup(
            jPanelPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TxtPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        Username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username.setText("User");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lertroslogo.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Group 3");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jLabelLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogout.setText("Logout");
        jLabelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelLogoutLayout = new javax.swing.GroupLayout(jPanelLogout);
        jPanelLogout.setLayout(jPanelLogoutLayout);
        jPanelLogoutLayout.setHorizontalGroup(
            jPanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelLogoutLayout.setVerticalGroup(
            jPanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelFrameLeftLayout = new javax.swing.GroupLayout(jPanelFrameLeft);
        jPanelFrameLeft.setLayout(jPanelFrameLeftLayout);
        jPanelFrameLeftLayout.setHorizontalGroup(
            jPanelFrameLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelQUEUE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelInvoid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelFrameLeftLayout.setVerticalGroup(
            jPanelFrameLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFrameLeftLayout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelQUEUE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelInvoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(jPanelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanelFrameLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 650));

        jPanelFrameTop.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanelFrameTopLayout = new javax.swing.GroupLayout(jPanelFrameTop);
        jPanelFrameTop.setLayout(jPanelFrameTopLayout);
        jPanelFrameTopLayout.setHorizontalGroup(
            jPanelFrameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        jPanelFrameTopLayout.setVerticalGroup(
            jPanelFrameTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelFrameTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 890, 30));

        jPanelMainQueue.setBackground(new java.awt.Color(204, 204, 204));
        jPanelMainQueue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Print");
        jPanelMainQueue.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 129, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Reset");
        jPanelMainQueue.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 129, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("07:00");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("01/01/2022");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        jLabel7.setText("01");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setText("Queue");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lertroslogo.png"))); // NOI18N
        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel8)))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(106, 106, 106))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jLabel5)
                .addGap(12, 12, 12)
                .addComponent(jLabel8)
                .addGap(14, 14, 14))
        );

        jPanelMainQueue.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 300, 480));

        jTabbedPaneMainApp.addTab("tab1", jPanelMainQueue);

        jPanelMainMenu.setBackground(new java.awt.Color(255, 153, 153));
        jPanelMainMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTxtMainMenu.setBackground(new java.awt.Color(200, 200, 200));

        TxtMenuSelect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtMenuSelect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtMenuSelect.setText("MENU");
        TxtMenuSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtMenuSelectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtMenuSelect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtMenuSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        TxtMenuEditSelect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtMenuEditSelect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtMenuEditSelect.setText("MENU EDIT");
        TxtMenuEditSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtMenuEditSelectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtMenuEditSelect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtMenuEditSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelTxtMainMenuLayout = new javax.swing.GroupLayout(jPanelTxtMainMenu);
        jPanelTxtMainMenu.setLayout(jPanelTxtMainMenuLayout);
        jPanelTxtMainMenuLayout.setHorizontalGroup(
            jPanelTxtMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTxtMainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(648, Short.MAX_VALUE))
        );
        jPanelTxtMainMenuLayout.setVerticalGroup(
            jPanelTxtMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTxtMainMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTxtMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        jPanelMainMenu.add(jPanelTxtMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 60));

        jPanelMenuSelect.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Menu :");

        TxtStock.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TxtStock.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ccbCategory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ccbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ก๋วยเตี๋ยว", "อาหารจานเด็ด", "อาหารจานชุด", "อาหารสั่งเพิ่ม", "อาหารจานเดียว", "อาหารสั่งเพิ่ม" }));

        cbbMenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ก๋วยเตี๋ยว ต้มยำหมู + หมูเด้ง (น้ำใสใส่ถั่ว)", "ก๋วยเตี๋ยว ชิ้นปลา + ชิ้นกุ้ง", "เย็นตาโฟ ทรงเครื่อง", "เย็นตาโฟ ต้มยำทะเล", "ก๋วยเตี๋ยว ต้มยำน้ำข้น ทะเล" }));

        ButtonAddProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonAddProduct.setText("ADD");
        ButtonAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddProductActionPerformed(evt);
            }
        });

        TbPayment.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TbPayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TB", "MENU", "Quanity", "Price", "Total", "Detail", "Status"
            }
        ));
        TbPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TbPayment.setRowHeight(40);
        jScrollPane1.setViewportView(TbPayment);

        TxtAreaDetail.setColumns(20);
        TxtAreaDetail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtAreaDetail.setRows(5);
        jScrollPane2.setViewportView(TxtAreaDetail);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Detail :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Stock :");

        ButtonEditProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonEditProduct.setText("EDIT");

        ButtonDeleteProduct.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ButtonDeleteProduct.setText("DELETE");

        TxtQuanity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtQuanity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TxtQuanity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtQuanityActionPerformed(evt);
            }
        });

        ButtonConfirm1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonConfirm1.setText("CONFIRM");
        ButtonConfirm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirm1ActionPerformed(evt);
            }
        });

        txtPriceSt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPriceSt.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Table :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Quanity :");

        cbbTable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        javax.swing.GroupLayout jPanelMenuSelectLayout = new javax.swing.GroupLayout(jPanelMenuSelect);
        jPanelMenuSelect.setLayout(jPanelMenuSelectLayout);
        jPanelMenuSelectLayout.setHorizontalGroup(
            jPanelMenuSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuSelectLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelMenuSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuSelectLayout.createSequentialGroup()
                        .addGroup(jPanelMenuSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMenuSelectLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMenuSelectLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanelMenuSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanelMenuSelectLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cbbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelMenuSelectLayout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ccbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelMenuSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelMenuSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbbTable, 0, 1, Short.MAX_VALUE)
                                    .addComponent(TxtQuanity, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanelMenuSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ButtonAddProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonEditProduct, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonDeleteProduct, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                        .addComponent(txtPriceSt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jScrollPane1)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMenuSelectLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonConfirm1)
                .addContainerGap())
        );
        jPanelMenuSelectLayout.setVerticalGroup(
            jPanelMenuSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuSelectLayout.createSequentialGroup()
                .addGroup(jPanelMenuSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMenuSelectLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(txtPriceSt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMenuSelectLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ButtonAddProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonEditProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonDeleteProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanelMenuSelectLayout.createSequentialGroup()
                        .addGroup(jPanelMenuSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMenuSelectLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanelMenuSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(TxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelMenuSelectLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanelMenuSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ccbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(cbbTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(16, 16, 16)
                        .addGroup(jPanelMenuSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(TxtQuanity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonConfirm1)
                .addGap(10, 10, 10))
        );

        jTabbedPaneMainMenu.addTab("tab1", jPanelMenuSelect);

        jPanelMENUEDIT.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("MENU");

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setText("ADD");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton5.setText("DELETE");

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ก๋วยเตี๋ยว", "อาหารจานเด็ด", "อาหารจานชุด", "อาหารสั่งเพิ่ม", "อาหารจานเดียว", "อาหารสั่งเพิ่ม" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("MENU");

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton6.setText("UPDATE");

        javax.swing.GroupLayout jPanelMENUEDITLayout = new javax.swing.GroupLayout(jPanelMENUEDIT);
        jPanelMENUEDIT.setLayout(jPanelMENUEDITLayout);
        jPanelMENUEDITLayout.setHorizontalGroup(
            jPanelMENUEDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMENUEDITLayout.createSequentialGroup()
                .addGroup(jPanelMENUEDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMENUEDITLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(jPanelMENUEDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMENUEDITLayout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelMENUEDITLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6))
                    .addGroup(jPanelMENUEDITLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMENUEDITLayout.setVerticalGroup(
            jPanelMENUEDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMENUEDITLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(jPanelMENUEDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelMENUEDITLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jTabbedPaneMainMenu.addTab("tab2", jPanelMENUEDIT);

        jPanelMainMenu.add(jTabbedPaneMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 890, -1));

        jTabbedPaneMainApp.addTab("tab3", jPanelMainMenu);

        jPanelMainInvoice.setBackground(new java.awt.Color(204, 204, 204));

        jTable3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TableNumber", "Invoice_ID", "Detil", "Quanity", "Price", "TotalPrice"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton7.setText("Print ALL");

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Print");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel14.setText("INVOICE");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("NUMBER :");

        javax.swing.GroupLayout jPanelMainInvoiceLayout = new javax.swing.GroupLayout(jPanelMainInvoice);
        jPanelMainInvoice.setLayout(jPanelMainInvoiceLayout);
        jPanelMainInvoiceLayout.setHorizontalGroup(
            jPanelMainInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainInvoiceLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelMainInvoiceLayout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addGroup(jPanelMainInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelMainInvoiceLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(12, 12, 12))
                    .addGroup(jPanelMainInvoiceLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainInvoiceLayout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(30, 30, 30)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMainInvoiceLayout.setVerticalGroup(
            jPanelMainInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainInvoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMainInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanelMainInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneMainApp.addTab("tab4", jPanelMainInvoice);

        jPanelMainPayment.setBackground(new java.awt.Color(0, 153, 153));
        jPanelMainPayment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTxtMainPayment.setBackground(new java.awt.Color(200, 200, 200));

        TxtPaymentSelect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtPaymentSelect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtPaymentSelect.setText("PAYMENT");
        TxtPaymentSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtPaymentSelectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtPaymentSelect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtPaymentSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        TxtAuditSelect.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtAuditSelect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxtAuditSelect.setText("AUDIT");
        TxtAuditSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtAuditSelectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtAuditSelect, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TxtAuditSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelTxtMainPaymentLayout = new javax.swing.GroupLayout(jPanelTxtMainPayment);
        jPanelTxtMainPayment.setLayout(jPanelTxtMainPaymentLayout);
        jPanelTxtMainPaymentLayout.setHorizontalGroup(
            jPanelTxtMainPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTxtMainPaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(648, Short.MAX_VALUE))
        );
        jPanelTxtMainPaymentLayout.setVerticalGroup(
            jPanelTxtMainPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTxtMainPaymentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTxtMainPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
        );

        jPanelMainPayment.add(jPanelTxtMainPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 60));

        jPanelPaymentSelect.setBackground(new java.awt.Color(204, 204, 204));

        TbPaymentFramePayment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TbPaymentFramePayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TB", "MENU", "Quantity", "Price", "Total", "Status"
            }
        ));
        TbPaymentFramePayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbPaymentFramePaymentMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(TbPaymentFramePayment);

        TxtST.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtST.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Sub Total :");

        TxtChange.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtChange.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        TxtCash.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TxtCash.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Cash :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Change :");

        ButtonConfirm2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonConfirm2.setText("CONFIRM");
        ButtonConfirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirm2ActionPerformed(evt);
            }
        });

        ButtonConfirm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ButtonConfirm.setText("ADD CASH");
        ButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPaymentSelectLayout = new javax.swing.GroupLayout(jPanelPaymentSelect);
        jPanelPaymentSelect.setLayout(jPanelPaymentSelectLayout);
        jPanelPaymentSelectLayout.setHorizontalGroup(
            jPanelPaymentSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPaymentSelectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPaymentSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPaymentSelectLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanelPaymentSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelPaymentSelectLayout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(TxtST, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ButtonConfirm))
                        .addGap(6, 6, 6)
                        .addGroup(jPanelPaymentSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtCash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonConfirm2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtChange, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addContainerGap())
        );
        jPanelPaymentSelectLayout.setVerticalGroup(
            jPanelPaymentSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPaymentSelectLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPaymentSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPaymentSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(TxtChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPaymentSelectLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanelPaymentSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel20))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPaymentSelectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonConfirm2)
                    .addComponent(ButtonConfirm)))
        );

        jTabbedPaneMainPayment.addTab("tab1", jPanelPaymentSelect);

        jPanelAudit.setBackground(new java.awt.Color(204, 204, 204));

        jTable4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "AmountInvoice", "Total"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jComboBox4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton9.setText("Print");

        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        javax.swing.GroupLayout jPanelAuditLayout = new javax.swing.GroupLayout(jPanelAudit);
        jPanelAudit.setLayout(jPanelAuditLayout);
        jPanelAuditLayout.setHorizontalGroup(
            jPanelAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAuditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAuditLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addGap(325, 325, 325))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAuditLayout.createSequentialGroup()
                .addContainerGap(380, Short.MAX_VALUE)
                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
        );
        jPanelAuditLayout.setVerticalGroup(
            jPanelAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAuditLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanelAuditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPaneMainPayment.addTab("tab2", jPanelAudit);

        jPanelMainPayment.add(jTabbedPaneMainPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 890, 600));

        jTabbedPaneMainApp.addTab("tab5", jPanelMainPayment);

        getContentPane().add(jTabbedPaneMainApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 890, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtQUEUEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtQUEUEMouseClicked
        // TODO add your handling code here:
        jTabbedPaneMainApp.setSelectedIndex(0);//home
    }//GEN-LAST:event_TxtQUEUEMouseClicked

    private void TxtMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtMenuMouseClicked
        jTabbedPaneMainApp.setSelectedIndex(1);//menu
    }//GEN-LAST:event_TxtMenuMouseClicked

    private void TxtInvoidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtInvoidMouseClicked
        jTabbedPaneMainApp.setSelectedIndex(2);
    }//GEN-LAST:event_TxtInvoidMouseClicked

    private void TxtPaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtPaymentMouseClicked
       jTabbedPaneMainApp.setSelectedIndex(3);
    }//GEN-LAST:event_TxtPaymentMouseClicked

    private void jLabelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMouseClicked
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelLogoutMouseClicked

    private void TxtPaymentSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtPaymentSelectMouseClicked
        jTabbedPaneMainPayment.setSelectedIndex(0);
    }//GEN-LAST:event_TxtPaymentSelectMouseClicked

    private void TxtAuditSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtAuditSelectMouseClicked
       jTabbedPaneMainPayment.setSelectedIndex(1);
    }//GEN-LAST:event_TxtAuditSelectMouseClicked

    private void TxtMenuSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtMenuSelectMouseClicked
        jTabbedPaneMainMenu.setSelectedIndex(0);
    }//GEN-LAST:event_TxtMenuSelectMouseClicked

    private void TxtMenuEditSelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtMenuEditSelectMouseClicked
        jTabbedPaneMainMenu.setSelectedIndex(1);
    }//GEN-LAST:event_TxtMenuEditSelectMouseClicked

    private void TxtQuanityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtQuanityActionPerformed
        
    }//GEN-LAST:event_TxtQuanityActionPerformed

    private void ButtonConfirm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirm1ActionPerformed

    }//GEN-LAST:event_ButtonConfirm1ActionPerformed

    private void ButtonAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddProductActionPerformed
         Vector v = new Vector(); //นำข้อมูลมาเก็บในเว็กเตอร์แล้วค่อยกระจายข้อมูลลงในตาราง
        if (TxtQuanity.getText().isEmpty()) { //ถ้าจำนวนเป็นค่าว่างให้แสดงผลเตือน
            JOptionPane.showMessageDialog(this, "Pls Input Quanity!!!", "", JOptionPane.ERROR_MESSAGE);
        }

        if (check()) {
            //เพิ่มจำนวนเข้าไปก่อนหน้า
            int a = Integer.parseInt(model.getValueAt(n, 2).toString()) + Integer.parseInt(TxtQuanity.getText()); // a =จำนวนเดิมที่เพิ่มเข้าไปก่อนหน้า +เพิ่มจำนวนที่เพิ่มเข้าไปใหม่
            model.setValueAt(a, n, 2); //นำข้อมูลของ a ลงไป ในแถวที่เลือกและคอลัมที่ 2
            System.out.println("a = " + a);
            //หาจำนวนเงินของแต่ละรายการ
            double price = a * Double.valueOf(TbPayment.getValueAt(n, 3).toString());
            System.out.println("จำนวนเงินใหม่ + " + price);
            model.setValueAt(df.format(price), n, 4); //นำราคาใหม่มาแสดงแถวที่เลือกคอลัมที่ 3
            //หาค่ารวม
            money = Double.valueOf(txtPriceSt.getText()) * Double.valueOf(TxtQuanity.getText()); //หาจำนวนเงินแต่ละรายการที่ต้องจ่าย โดยราคา * จำนวน 
            total += money;
            
        } else {
            v.add(cbbTable.getSelectedItem().toString());
            v.add(cbbMenu.getSelectedItem().toString()); //รายการอาหาร
            v.add(TxtQuanity.getText());//จำนวน
            v.add(txtPriceSt.getText());//ราคาชุด
            money = Double.valueOf(txtPriceSt.getText()) * Double.valueOf(TxtQuanity.getText()); //หาจำนวนเงินแต่ละรายการที่ต้องจ่าย โดยราคา * จำนวน
            v.add(df.format(money));// เก็บค่าลงจำนวนเงืนลงในตาราง
            v.add(TxtAreaDetail.getText());
            v.add("ยังไม่ได้จ่าย");
    
            
            model.addRow(v); //นำข้อมูลใน เว็กเตอร์ลงตารางและแสดงผลเรียงจาก รายอาการอาหาร ราคา จำนวน จำนวนเงิน ตามลำดับ 
            TxtQuanity.requestFocus();
            TxtQuanity.setText("");
        }
    }//GEN-LAST:event_ButtonAddProductActionPerformed

    private void TbPaymentFramePaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbPaymentFramePaymentMouseClicked

    }//GEN-LAST:event_TbPaymentFramePaymentMouseClicked

    private void ButtonConfirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirm2ActionPerformed


    }//GEN-LAST:event_ButtonConfirm2ActionPerformed

    private void ButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonConfirmActionPerformed
  
    }//GEN-LAST:event_ButtonConfirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddProduct;
    private javax.swing.JButton ButtonConfirm;
    private javax.swing.JButton ButtonConfirm1;
    private javax.swing.JButton ButtonConfirm2;
    private javax.swing.JButton ButtonDeleteProduct;
    private javax.swing.JButton ButtonEditProduct;
    private javax.swing.JLabel Logo;
    private javax.swing.JTable TbPayment;
    private javax.swing.JTable TbPaymentFramePayment;
    private javax.swing.JTextArea TxtAreaDetail;
    private javax.swing.JLabel TxtAuditSelect;
    private javax.swing.JTextField TxtCash;
    private javax.swing.JTextField TxtChange;
    private javax.swing.JLabel TxtInvoid;
    private javax.swing.JLabel TxtMenu;
    private javax.swing.JLabel TxtMenuEditSelect;
    private javax.swing.JLabel TxtMenuSelect;
    private javax.swing.JLabel TxtPayment;
    private javax.swing.JLabel TxtPaymentSelect;
    private javax.swing.JLabel TxtQUEUE;
    private javax.swing.JTextField TxtQuanity;
    private javax.swing.JTextField TxtST;
    private javax.swing.JTextField TxtStock;
    private javax.swing.JLabel Username;
    private javax.swing.JComboBox<String> cbbMenu;
    private javax.swing.JComboBox<String> cbbTable;
    private javax.swing.JComboBox<String> ccbCategory;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelAudit;
    private javax.swing.JPanel jPanelFrameLeft;
    private javax.swing.JPanel jPanelFrameTop;
    private javax.swing.JPanel jPanelInvoid;
    private javax.swing.JPanel jPanelLogout;
    private javax.swing.JPanel jPanelMENUEDIT;
    private javax.swing.JPanel jPanelMainInvoice;
    private javax.swing.JPanel jPanelMainMenu;
    private javax.swing.JPanel jPanelMainPayment;
    private javax.swing.JPanel jPanelMainQueue;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JPanel jPanelMenuSelect;
    private javax.swing.JPanel jPanelPayment;
    private javax.swing.JPanel jPanelPaymentSelect;
    private javax.swing.JPanel jPanelQUEUE;
    private javax.swing.JPanel jPanelTxtMainMenu;
    private javax.swing.JPanel jPanelTxtMainPayment;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPaneMainApp;
    private javax.swing.JTabbedPane jTabbedPaneMainMenu;
    private javax.swing.JTabbedPane jTabbedPaneMainPayment;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtPriceSt;
    // End of variables declaration//GEN-END:variables
}
